# Generated by Django 5.2.1 on 2025-05-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='anonym', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
